feed/urls.py
from django.urls import path

from . import views

app_name = 'feed'

urlpatterns = [
    path("", views.HomePage.as_view(), name='index'),
    path("<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    path("new/", views.CreateNewPost.as_view(), name='new_post' )
]

profiles/urls.py
from django.urls import path
from . import views

app_name = "profiles"

urlpatterns =[
    path("<str:username>", views.ProfileDetailView.as_view(), name='detail'),
    path("<str:username>/follow", views.FollowView.as_view(), name='follow'),
]

til/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.conf.urls.static import static
from feed import urls as feed_urls
from django.conf import settings
from profiles import urls as profile_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
    path('profile/', include(profile_urls, namespace='profile')),
    re_path("", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=120)
    text = models.CharField(max_length=240)
    date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE )

    def __str__(self):
        return self.title[0:100]

followers/models.py
from django.db import models
from django.contrib.auth.models import User

class Follower(models.Model):
    followed_by = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name="followed_by"
    )
    following = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name="following"
    )

    def __str__(self) -> str:
        return f"{self.followed_by.id} is following {self.following.id}"

    ## only once can you follow others
    class Meta:
        unique_together = ('followed_by', 'following')

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail import ImageField

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    image = ImageField(upload_to='profiles')


    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    ## create profile when new user created
    if created:
        Profile.objects.create(user=instance)

feed/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render
from django.views.generic import DetailView, TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from followers.models import Follower
from .models import Post

class HomePage(TemplateView):
    http_method_names = ["get"]
    template_name = "feed/homepage.html"
    
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            following = list(Follower.objects.filter(followed_by=self.request.user).values_list('following', flat=True))
            if not following:
                posts = Post.objects.all().order_by('-id')[0:30] 
            else:  
                posts= Post.objects.filter(author__in=following).order_by('-id')[0:60]  
        else:
            posts = Post.objects.all().order_by('-id')[0:30]
        context['posts'] = posts 
        return context

## forcing to auth, can't create post without login
class PostDetailView(LoginRequiredMixin, DetailView):
    http_method_names= ["get"]
    template_name = 'feed/detail.html'
    model = Post
    context_object_name = 'post'

class CreateNewPost(CreateView):
    template_name = "feed/create.html"
    model = Post
    fields = ['title', 'text']
    success_url = "/"

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.save()
        return super().form_valid(form)
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        post = Post.objects.create(
            text = request.POST.get("text"),
            title = request.POST.get("title"),
            author = request.user
        )
        return render(
            request,
            "includes/post.html",
            {
                "post": post,
                "show_detail_link": True
            },
           content_type="application/html" 
        )

followers/views.py
from django.shortcuts import render

# Create your views here.

profiles/views.py
from typing import Any
from django.contrib.auth.models import User
from django.http.request import HttpRequest as HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.views.generic import DetailView, View
from feed.models import Post
from followers.models import Follower
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest


class ProfileDetailView(DetailView):
    http_method_names = ['get']
    template_name = "profiles/detail.html"
    model = User
    context_object_name = "user"
    slug_field = "username"
    slug_url_kwarg = "username"

    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['total_posts'] = Post.objects.filter(author=user).count()
        context['followers'] = Follower.objects.filter(following=user).count()
        if self.request.user.is_authenticated:
            context["you_follow"] = Follower.objects.filter(following=user, followed_by=self.request.user).exists()
        return context
    
class FollowView(LoginRequiredMixin, View):
    http_method_names = ["post"]

    def post(self, request, *args, **kwargs):
        data = request.POST.dict()
        if "action" not in data or "username" not in data:
            return HttpResponseBadRequest("Missing Data")
        
        try: 
            other_user = User.objects.get(username=data["username"])
        except User.DoesNotExist:
            return HttpResponseBadRequest("Missing user")
        
        if data['action'] == "follow":
        #Follow
            follower, created = Follower.objects.get_or_create(
            followed_by = request.user,
            following= other_user 
            )
        else:
            try:
        #Unfollow
                follower = Follower.objects.get(
                    followed_by = request.user,
                    following= other_user, 
                 )
            except Follower.DoesNotExist:
                follower = None

            if follower:
                follower.delete()
        return JsonResponse({
            'success': True,
            'wording': "Unfollow" if data['action'] == "follow" else "Follow"
        })

feed/templates/feed/create.html
{% extends 'base.html'%}

{% block title %}Create a new post!{% endblock %}
{% block body %}
    <form action="." method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="flex items-center justify-center">
            <div class="my-3">
            <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center" type="submit" >
                <span class="mr-2">Create Post</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
                </svg>
            </button>
        </div> 
    </form>
{% endblock %}

feed/templates/feed/detail.html
{% extends 'base.html'%}


{% block title %}{{post.text}} by {{post.author.username}}{% endblock %}

{% block body %}
    {% include "includes/post.html" with post=post %}
{% endblock %}

feed/templates/feed/homepage.html
{% extends "base.html" %}

{% block title %}Hello on my webpage{% endblock %}

{% block body %}
    <div id="post-container">
        {% for post in posts%}
            {% include "includes/post.html" with post=post show_detail_link=True %}
                <hr>
        {% endfor %}
    </div>
   
{% endblock %}

profiles/templates/profiles/detail.html
{% extends 'base.html'%}
{% load thumbnail %}

{% block title %}{{user.username}}'s profile{% endblock %}

{% block body %}
  <!-- component -->
<div class="rounded-3xl overflow-hidden shadow-xl max-w-xs my-3 bg-blue-500">
    <img src="https://i.imgur.com/dYcYQ7E.png" class="w-full" />
  <div class="flex justify-center -mt-8">
         {% thumbnail user.profile.image "150x150" crop="center" as im %}
            <img class="rounded-full border-solid border-white border-2 -mt-3" src="{{ im.url }}" alt="avatar">
         {% endthumbnail %}	
  </div>
  <div class="text-center px-3 pb-6 pt-2">
      <h3 class="text-white text-xl font-bold font-sans">{{user.username}}</h3>
      {% if request.user.is_authenticated %}
        {% if request.user != user %}
      <div class="mt-3">
        <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-green-500 hover:border-green-600 
            hover:bg-green-500 hover:text-white shadow-md py-1 px-3 inline-flex items-center text-sm mt-4 js-follow" 
            data-username="{{user.username}}" type="button"
            data-action="{% if you_follow%}un{% endif %}follow" data-url="{% url 'profiles:follow' user.username %}"
            >
            <span class="mr-2 js-follow-text ">
                {% if you_follow%}
                Unfollow
                {% else%}
                Follow
                {% endif %}
            </span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
        </button>
      </div>
        {% endif %}
      {% else %}
      <div class="mt-3 text-xl ">
        Login to follow this user
      </div>
      {% endif %}
  </div>
    <div class="flex justify-center pb-3 text-white">
    <div class="text-center mr-3 border-r pr-3">
      <h2>{{total_posts}}</h2>
      <span>Posts</span>
    </div>
    <div class="text-center">
      <h2>{{followers}}</h2>
      <span>Followers</span>
    </div>
    </div>
</div>
{% endblock %}

til/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    here i AMDFG
</body>
</html>